- name: Demo on filters
  hosts: local
  connection: local
  tasks:
  - name: demo on filters Greetings
    ansible.builtin.debug:
      msg: "Hi Deekshith Padmanabha {{ Greeting | default ('Good Morning') }}"