- name: Demo on map to list
  hosts: local
  connection: local
  tags:
    name: ansible
    project: Roboshop
    component: catalogue

  tasks:
  - name: convert map to list
    ansible.builtin.debug:
      msg: "{{ tags | dict2items }}"  